import Head from "next/head";
import { api } from "~/utils/api";
import { useState } from "react";
import StartPuzzle from "./StartPuzzle";

export default function Home() {
  // const [move, setMove] = useState('');
  // const { data } = api.puzzles.getOne.useQuery({difficulty: 'hard'});
  // const handleChange = (event) => {
  //   setMove(event.target.value);
  // }

  // console.log('move', move);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full overflow-y-scroll md:max-w-2xl">
          {/* <input
            className="grow bg-transparent outline-none"
            type="text"
            value={move}
            onChange={handleChange}
          /> */}
          <StartPuzzle />
        </div>
        {/* <button >MOVE</button> */}
      </main>
    </>
  );
}
